### ISSUE TITLE
Reorganize File Structure

### ISSUE THREAD

**Issue by alex-stout** [clearwater-labs/uwecApp#8]
1. The styles need to be broken out. We can't maintain and manage a single huge block of styles. Make sure to break out component specific styles.
2. The same goes for components. We need a good way to organize these so we don't have a flat file hierarchy making it hard to find things.

**Comment by SullivanPrell** [comment]
File structure updated for screens, app components, images, and stylesheets. 
Work in progress for separating and cleaning up the styles.

**Comment by SullivanPrell** [comment]
Style sheets are now split by the associated app screen. All new app screens should be within the `/screens` folder, and all style sheets should be included in the `/assets/styles/` folder. Images are now located in the `/assets/images/` folder.
